### ISSUE TITLE
How to get it autoplay

### ISSUE THREAD

**Issue by muhaimincs** [Emiliano-Bucci/react-spring-carousel-js#1]

**Comment by Emiliano-Bucci** [comment]
@muhaimincs Hi! Sorry for the delay :) The `autoplay` functionality isn't built inside the Carousel, as every developer may have particular/different needs, and i wanted to maximum the extensibility of the library (no bounds). In order to implement the `autoplay` functionality you can do the following: 

```
useEffect(() => {
    const interval = setInterval(() => {
      slideToNextItem();
    }, 3000);

    return () => {
      window.clearInterval(interval);
    };
  }, [slideToNextItem]);

return (
   <div>{carouselFragment}</div>
) 
```

Let me know if you need anything else! :)

**Comment by muhaimincs** [comment]
understood. Thanks!
